workflows:
  default-workflow:
    name: Manga Studio Pro Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - congtintruong@gmail.com # Email của bạn để nhận thông báo build xong