workflows:
  default-workflow:
    name: Manga Studio Final
    instance_type: mac_mini_m2
    scripts:
      - name: Build App
        script: | 
          flutter pub get
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app